synthetic_pdf:
#  seed: 2
  amount: 4
  generator_type: "latex"

pipeline:
#  generate_pdfs: true
#  parse_pdfs: true
  extract_segments: true
#  evaluate_results: true
  reuse_timestamp: "2025-08-26_12-54-12"  # Set to existing timestamp when generate_pdfs is false
  formula_llm_judge_model: "gpt-5-nano"


# Parser Configuration - List of enabled parsers
parsers:
#  - nanonets_ocr_s
#  - ocrflux
#  - got_ocr
  - mistral
  - llamaparse
  - marker-openai
  - marker-gemini
  - megaparse
  - openai_gpt-4o
  - openai_gpt-4o-mini
  - gemini-2.5-pro
  - gemini-2.5-flash
  - mineru
  - mathpix
#  - docling


#Deprecated:
#  - unstructured
#  - pymupdf
#  - pypdf
#  - adobe


